compressionLevel: mixed

enableGlobalCache: false

yarnPath: .yarn/releases/yarn-4.0.2.cjs

packageExtensions:
  debug@*:
    dependencies:
      supports-color: '8.1.1'
  next@*:
    dependencies:
      sass: '*'